from spaceone.core.error import *


class ERROR_NOT_FOUND_TRUSTED_SERVICE_ACCOUNT_ID(ERROR_BASE):
    _message = 'A trusted_service_account_id "{trusted_service_account_id}" is not exist in domain.'
